services:
  # Note: MariaDB is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/mariadb
  db:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    # image: mariadb:lts recommended was 10.11. lts was ARG MARIADB_VERSION=1:11.8.3+maria~ubu2404
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      # - db:/var/lib/mysql:Z #- changed the volume to a bind mount
      - ./mariadb_volume:/var/lib/mysql:Z
    environment:
      #- MYSQL_ROOT_PASSWORD= moved to db.env
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  # Note: Redis is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/redis
  redis:
    # image: redis:alpine - replaced with the actual tag so I can control the image updates
    image: redis:alpine3.22
    restart: always

  app:
    # image: nextcloud:apache - replaced with the actual tag so I can control the image updates
    image: nextcloud:31.0.8-apache
    restart: always
    expose:
      - 80
    # ports:
    #   - 80:80
    volumes:
      # - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
      # Add bind mounts and seperate volumes for better control and persistence
      - ./nextcloud_data:/var/www/html/data:z
    environment:
      # - VIRTUAL_HOST=nextcloud.kgune.com
      # - LETSENCRYPT_HOST=nextcloud.kgune.com
      # - LETSENCRYPT_EMAIL=kum.kgune@gmail.com
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      # Auto-install admin (one-time, first run)
      - NEXTCLOUD_ADMIN_USER=nextcloud-admin
      - NEXTCLOUD_ADMIN_PASSWORD=ChangeMeNow!
      # Behind reverse proxy / NPM
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.kgune.com
      - TRUSTED_PROXIES=npm   # or your proxy container name or subnet, e.g. 172.18.0.0/16
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.kgune.com
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    # image: nextcloud:apache - replaced with the actual tag so I can control the image updates
    image: nextcloud:31.0.8-apache
    restart: always
    volumes:
      # - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
      # Add bind mounts and seperate volumes for better control and persistence
      - ./nextcloud_data:/var/www/html/data:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"   # NPM admin UI
      - "443:443"
    volumes:
      - ./proxy_data:/data
      - ./proxy_letsencrypt:/etc/letsencrypt
    networks:
      - proxy-tier

  static-site:
    build: ./simple_static_webpage
    container_name: static-site
    restart: unless-stopped
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: false