services:
  # Note: MariaDB is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/mariadb
  db:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    # image: mariadb:lts recommended was 10.11. lts was ARG MARIADB_VERSION=1:11.8.3+maria~ubu2404
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      # - db:/var/lib/mysql:Z #- changed the volume to a bind mount
      - ./mariadb_volume:/var/lib/mysql:Z
    environment:
      #- MYSQL_ROOT_PASSWORD= moved to db.env
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  # Note: Redis is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/redis
  redis:
    # image: redis:alpine - replaced with the actual tag so I can control the image updates
    image: redis:alpine3.22
    restart: always

  app:
    # image: nextcloud:apache - replaced with the actual tag so I can control the image updates
    image: nextcloud:31.0.8-apache
    restart: always
    expose:
      - 80
    # ports:
    #   - 80:80
    volumes:
      # - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
      # Add bind mounts and seperate volumes for better control and persistence
      - ./nextcloud_instalation:/var/www/html:z
      - ./nextcloud_apps:/var/www/html/custom_apps:z
      - ./nextcloud_config:/var/www/html/config:z
      - ./nextcloud_data:/var/www/html/data:z
    environment:
      # - VIRTUAL_HOST=nextcloud.kgune.com
      # - LETSENCRYPT_HOST=nextcloud.kgune.com
      # - LETSENCRYPT_EMAIL=kum.kgune@gmail.com
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
      - proxy
    networks:
      - proxy-tier
      - default

  cron:
    # image: nextcloud:apache - replaced with the actual tag so I can control the image updates
    image: nextcloud:31.0.8-apache
    restart: always
    volumes:
      # - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
      # Add bind mounts and seperate volumes for better control and persistence
      - ./nextcloud_instalation:/var/www/html:z
      - ./nextcloud_apps:/var/www/html/custom_apps:z
      - ./nextcloud_config:/var/www/html/config:z
      - ./nextcloud_data:/var/www/html/data:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  static-site:
    build: ./simple_static_webpage
    container_name: static-site
    expose:
      - 80
    environment:
      # - VIRTUAL_HOST=ddns.kgune.com
      # - LETSENCRYPT_HOST=ddns.kgune.com
      # - LETSENCRYPT_EMAIL=kum.kgune@gmail.com
    restart: unless-stopped
    depends_on:
      - proxy
    networks:
      - proxy-tier
      - default

# # Note: Nginx-proxy is an external service. You can find more information about the configuration here:
# # Warning: Do not use :latest tags of nginx-proxy unless absolutely sure about the consequences.
# # https://hub.docker.com/r/nginxproxy/nginx-proxy
# proxy:
#   build: ./proxy
#   restart: always
#   ports:
#     - 80:80
#     - 443:443
#   labels:
#     - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
#   volumes:
#     - certs:/etc/nginx/certs:ro,z
#     - vhost.d:/etc/nginx/vhost.d:z
#     - html:/usr/share/nginx/html:z
#     - dhparam:/etc/nginx/dhparam:z
#     - /var/run/docker.sock:/tmp/docker.sock:z,ro
#   networks:
#     - proxy-tier

# # Note: Letsencrypt companion is an external service. You can find more information about the configuration here:
# # https://hub.docker.com/r/nginxproxy/acme-companion
# letsencrypt-companion:
#   image: nginxproxy/acme-companion
#   restart: always
#   environment:
#     - DEFAULT_EMAIL=
#   volumes:
#     - certs:/etc/nginx/certs:z
#     - acme:/etc/acme.sh:z
#     - vhost.d:/etc/nginx/vhost.d:z
#     - html:/usr/share/nginx/html:z
#     - /var/run/docker.sock:/var/run/docker.sock:z,ro
#   networks:
#     - proxy-tier
#   depends_on:
#     - proxy

proxy:
  image: 'jc21/nginx-proxy-manager:latest'
  restart: unless-stopped
  ports:
    # These ports are in format <host-port>:<container-port>
    - '80:80' # Public HTTP Port
    - '443:443' # Public HTTPS Port
    - '81:81' # Admin Web Port
  # Add any other Stream port you want to expose
  # - '21:21' # FTP

  #environment:
  # Uncomment this if you want to change the location of
  # the SQLite DB file within the container
  # DB_SQLITE_FILE: "/data/database.sqlite"

  # Uncomment this if IPv6 is not enabled on your host
  # DISABLE_IPV6: 'true'

  volumes:
    - ./data:/data
    - ./letsencrypt:/etc/letsencrypt
  networks:
     - proxy-tier

volumes:
# db: - used a bind mount instead
# nextcloud: - used a bind mount instead
# certs:
# acme:
# vhost.d:
# html:
# dhparam:

networks:
  proxy-tier:
